apiVersion: batch/v1
kind: Job
metadata:
  name: nodbox
spec:
  template:
    spec:
      containers:
        - name: nodbox
          image: ghcr.io/junminahn/nodbox:latest
          imagePullPolicy: Always
          args:
            - |
              console.log("hello world!");
              return "200:Okay";
      # imagePullSecrets:
      #   - name: gh-registry-config
      restartPolicy: Never
  backoffLimit: 1
